### PR TITLE
Fix filepath feature

### PR DESCRIPTION
**Pull request by ayatkyo**
This PR will fix crash when using the WebView2 SDK version below `1.0.1774.30`, and also fixed some possible memory leaks due to unreleased resources.

### CODE REVIEW

**Comment by leaanthony** [comment]
Thanks for opening this @ayatkyo 🙏 I'm in the middle of doing a capabilities API which will improve the way we can detect features. Are you ok if I get that in then update this PR?

**Comment by leaanthony** [comment]
I've added a [`hasCapability` function](https://github.com/wailsapp/go-webview2/blob/main/pkg/edge/capabilities.go) that you can now use to check if the method is available. An example of using it can be found [in the test](https://github.com/wailsapp/go-webview2/blob/main/pkg/edge/capabilities_test.go).

We'll be using this mechanism for all capability checks moving forward. Let me know if you need more information 👍

**Comment by ayatkyo** [comment]
Hi @leaanthony, Sorry for the late reply.

Thanks for the new function, this will make the capability check more organized, I will update the code.

I have a question, do we need to put the `FullPathResolver` in the list or just use `getAdditionalObjects`?

---

**From Wails PR**

> Am I right in thinking that if a webview runtime is installed which does not support GetAdditionalObjects,that means DnD is unavailable by default?

Yes, to get full file path, frontend needs to send the File object using `postMessageWithAdditionalObjects` then on the native side, we use `GetAdditionalObjects` alongside `GetValueAtIndex` to get the file object.

Unfortunately, we cannot simply just use `window.chrome.webview.postMessageWithAdditionalObjects` to check if this feature is supported, because I have checked that function is also available on WebView2 1.0.1722.45 which does not have `GetAdditionalObjects`.

**Comment by leaanthony** [comment]
I was wondering if the capability should really be called "DragAndDrop" as you can't really use it without the additional objects calls

**Comment by ayatkyo** [comment]
This feature is actually for resolving the full path of the js File object, and the drag and drop is one example of how we can use it, because we also can use this for normal file select, as long as we pass the js File object into `chrome.webview.postMessageWithAdditionalObjects`

For normal file select example is in https://github.com/ayatkyo/wails-2-file-drop-test/blob/611c70b08807c72066d393bde9f6d5a182237e2e/frontend/src/main.js#L7C1-L30

**Comment by leaanthony** [comment]
@ayatkyo - were you going to update this with the new capabilities API or did you want me to do that?

**Comment by leaanthony** [comment]
@ayatkyo - any updates?

**Comment by leaanthony** [comment]
@ayatkyo - any updates?

**Pull request merged**
